# Der Name deiner Pipeline, der in GitHub angezeigt wird
name: CI/CD Pipeline für Graph-Assistent 🚀

# 1. TRIGGER: Wann soll der Roboter 🤖 starten?
on:
  push:
    branches: [ "main" ]  # Jedes Mal, wenn du auf den "main" Branch hochlädst

# 2. JOBS: Was soll der Roboter tun?
jobs:
  # -----------------------------------------------
  # JOB 1: Der "Tester" 🧪
  # -----------------------------------------------
  test:
    name: 1. Code testen (PyTest)
    runs-on: ubuntu-latest  # Starte eine frische Linux-Maschine

    steps:
      # Schritt 1.1: Hole den Code aus deinem Repository
      - name: Code auschecken
        uses: actions/checkout@v4

      # Schritt 1.2: Installiere die richtige Python-Version
      - name: Python 3.10 einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Schritt 1.3: Installiere alle "Zutaten" (Bibliotheken)
      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt
          pip install pytest

      # Schritt 1.4: Führe den PyTest aus
      # HIER werden die Secrets (Schlüssel) 🔑 sicher übergeben
      - name: PyTests ausführen
        run: pytest
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

  # -----------------------------------------------
  # JOB 2: Der "Box-Packer" 📦 (KORRIGIERT)
  # -----------------------------------------------
  build-and-deploy:
    name: 2. Docker-Box bauen & bereitstellen
    runs-on: ubuntu-latest
    needs: test  # Starte NUR, wenn Job 1 (test) erfolgreich war!

    steps:
      # Schritt 2.1: Code auschecken
      - name: Code auschecken
        uses: actions/checkout@v4

      # Schritt 2.2: Bei ghcr.io anmelden
      - name: Bei GitHub Container Registry (ghcr.io) anmelden
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NEUER SCHRITT 2.3: Namen in Kleinbuchstaben umwandeln
      # Wir wandeln 'Osamaiqji89/llm-basics' in 'osamaiqji89/llm-basics' um
      - name: Namen in Kleinbuchstaben umwandeln
        id: lowercase_repo
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Schritt 2.4: Docker Image bauen und pushen
      - name: Docker Image bauen und pushen
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # HIER nutzen wir den neuen Kleinbuchstaben-Namen
          tags: ghcr.io/${{ steps.lowercase_repo.outputs.repo }}:latest